from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessDirection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(choices=[("panorama", "Панорама"), ("ro", "РО")], max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "business_directions", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CrmUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bitrix_id", models.PositiveBigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={"db_table": "crm_users", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("value", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={"db_table": "sync_cursors"},
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="bitrix24", max_length=64)),
                ("status", models.CharField(choices=[("started", "Started"), ("success", "Success"), ("failed", "Failed")], default="started", max_length=16)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
            ],
            options={"db_table": "sync_runs"},
        ),
        migrations.CreateModel(
            name="CrmPipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bitrix_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("direction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.businessdirection")),
            ],
            options={"db_table": "crm_pipelines", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CrmLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bitrix_id", models.PositiveBigIntegerField(unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("status_id", models.CharField(blank=True, max_length=128)),
                ("created_time", models.DateTimeField()),
                ("source_id", models.CharField(blank=True, max_length=128)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmuser")),
                ("direction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.businessdirection")),
            ],
            options={"db_table": "crm_leads"},
        ),
        migrations.CreateModel(
            name="CrmStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bitrix_id", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("sort", models.IntegerField(default=0)),
                ("is_zz", models.BooleanField(default=False)),
                ("is_zn", models.BooleanField(default=False)),
                ("is_success", models.BooleanField(default=False)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("pipeline", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmpipeline")),
            ],
            options={"db_table": "crm_stages", "ordering": ["pipeline_id", "sort", "name"]},
        ),
        migrations.CreateModel(
            name="CrmDeal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bitrix_id", models.PositiveBigIntegerField(unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("created_time", models.DateTimeField()),
                ("moved_time", models.DateTimeField(blank=True, null=True)),
                ("contract_date", models.DateField(blank=True, null=True)),
                ("contract_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmuser")),
                ("direction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.businessdirection")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmlead")),
                ("pipeline", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmpipeline")),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmstage")),
            ],
            options={"db_table": "crm_deals"},
        ),
        migrations.CreateModel(
            name="DealFirstZZ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_zz_at", models.DateTimeField()),
                ("source", models.CharField(default="stage_history", max_length=32)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmuser")),
                ("deal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="first_zz", to="analytics.crmdeal")),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmstage")),
            ],
            options={"db_table": "deal_first_zz"},
        ),
        migrations.CreateModel(
            name="DealStageEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage_id_raw", models.CharField(max_length=128)),
                ("changed_at", models.DateTimeField()),
                ("source_event_id", models.CharField(blank=True, max_length=128)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmuser")),
                ("deal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stage_events", to="analytics.crmdeal")),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="analytics.crmstage")),
            ],
            options={"db_table": "deal_stage_events"},
        ),
        migrations.CreateModel(
            name="ManagerDailyMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_date", models.DateField()),
                ("leads", models.PositiveIntegerField(default=0)),
                ("target_leads", models.PositiveIntegerField(default=0)),
                ("zz", models.PositiveIntegerField(default=0)),
                ("contracts", models.PositiveIntegerField(default=0)),
                ("contract_amount", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("direction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analytics.businessdirection")),
                ("manager", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analytics.crmuser")),
            ],
            options={"db_table": "manager_daily_metrics"},
        ),
        migrations.AddIndex(model_name="syncrun", index=models.Index(fields=["source", "started_at"], name="sync_runs_source__53367f_idx")),
        migrations.AddIndex(model_name="syncrun", index=models.Index(fields=["status", "started_at"], name="sync_runs_status__657735_idx")),
        migrations.AddIndex(model_name="crmstage", index=models.Index(fields=["pipeline", "is_zz"], name="crm_stages_pipelin_1548db_idx")),
        migrations.AddIndex(model_name="crmstage", index=models.Index(fields=["pipeline", "is_zn"], name="crm_stages_pipelin_9e01f3_idx")),
        migrations.AddIndex(model_name="crmlead", index=models.Index(fields=["created_time"], name="crm_leads_created_4cfa23_idx")),
        migrations.AddIndex(model_name="crmlead", index=models.Index(fields=["assigned_by", "created_time"], name="crm_leads_assigne_8c5e0b_idx")),
        migrations.AddIndex(model_name="crmlead", index=models.Index(fields=["direction", "created_time"], name="crm_leads_directi_caa372_idx")),
        migrations.AddIndex(model_name="crmdeal", index=models.Index(fields=["created_time"], name="crm_deals_created_285123_idx")),
        migrations.AddIndex(model_name="crmdeal", index=models.Index(fields=["contract_date"], name="crm_deals_contrac_7ea49e_idx")),
        migrations.AddIndex(model_name="crmdeal", index=models.Index(fields=["assigned_by", "created_time"], name="crm_deals_assigne_00e3c3_idx")),
        migrations.AddIndex(model_name="crmdeal", index=models.Index(fields=["assigned_by", "contract_date"], name="crm_deals_assigne_8f51ea_idx")),
        migrations.AddIndex(model_name="crmdeal", index=models.Index(fields=["direction", "created_time"], name="crm_deals_directi_c7b9ad_idx")),
        migrations.AddIndex(model_name="crmdeal", index=models.Index(fields=["pipeline", "stage"], name="crm_deals_pipelin_b2b85e_idx")),
        migrations.AddIndex(model_name="dealfirstzz", index=models.Index(fields=["first_zz_at"], name="deal_first__first_z_990169_idx")),
        migrations.AddIndex(model_name="dealfirstzz", index=models.Index(fields=["assigned_by", "first_zz_at"], name="deal_first__assigne_a0c214_idx")),
        migrations.AddIndex(model_name="dealstageevent", index=models.Index(fields=["deal", "changed_at"], name="deal_stage__deal_id_8bd4dc_idx")),
        migrations.AddIndex(model_name="dealstageevent", index=models.Index(fields=["stage_id_raw", "changed_at"], name="deal_stage__stage_i_5ca967_idx")),
        migrations.AddIndex(model_name="dealstageevent", index=models.Index(fields=["assigned_by", "changed_at"], name="deal_stage__assigne_f08a43_idx")),
        migrations.AddConstraint(model_name="dealstageevent", constraint=models.UniqueConstraint(fields=("deal", "stage_id_raw", "changed_at", "source_event_id"), name="uniq_deal_stage_event_source")),
        migrations.AddIndex(model_name="managerdailymetric", index=models.Index(fields=["metric_date"], name="manager_dai_metric__f1688d_idx")),
        migrations.AddIndex(model_name="managerdailymetric", index=models.Index(fields=["manager", "metric_date"], name="manager_dai_manager_40e04a_idx")),
        migrations.AddIndex(model_name="managerdailymetric", index=models.Index(fields=["direction", "metric_date"], name="manager_dai_directi_1ca1b6_idx")),
        migrations.AddConstraint(model_name="managerdailymetric", constraint=models.UniqueConstraint(fields=("metric_date", "manager", "direction"), name="uniq_manager_daily_metric")),
    ]

