from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_detail_views"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="crmdeal",
            new_name="crm_deals_created_9f1377_idx",
            old_name="crm_deals_created_285123_idx",
        ),
        migrations.RenameIndex(
            model_name="crmdeal",
            new_name="crm_deals_contrac_3a15c5_idx",
            old_name="crm_deals_contrac_7ea49e_idx",
        ),
        migrations.RenameIndex(
            model_name="crmdeal",
            new_name="crm_deals_assigne_d62fe8_idx",
            old_name="crm_deals_assigne_00e3c3_idx",
        ),
        migrations.RenameIndex(
            model_name="crmdeal",
            new_name="crm_deals_assigne_9f089c_idx",
            old_name="crm_deals_assigne_8f51ea_idx",
        ),
        migrations.RenameIndex(
            model_name="crmdeal",
            new_name="crm_deals_directi_35d365_idx",
            old_name="crm_deals_directi_c7b9ad_idx",
        ),
        migrations.RenameIndex(
            model_name="crmdeal",
            new_name="crm_deals_pipelin_688033_idx",
            old_name="crm_deals_pipelin_b2b85e_idx",
        ),
        migrations.RenameIndex(
            model_name="crmlead",
            new_name="crm_leads_created_328e19_idx",
            old_name="crm_leads_created_4cfa23_idx",
        ),
        migrations.RenameIndex(
            model_name="crmlead",
            new_name="crm_leads_assigne_ad04e5_idx",
            old_name="crm_leads_assigne_8c5e0b_idx",
        ),
        migrations.RenameIndex(
            model_name="crmlead",
            new_name="crm_leads_directi_243eef_idx",
            old_name="crm_leads_directi_caa372_idx",
        ),
        migrations.RenameIndex(
            model_name="crmstage",
            new_name="crm_stages_pipelin_c0e703_idx",
            old_name="crm_stages_pipelin_1548db_idx",
        ),
        migrations.RenameIndex(
            model_name="crmstage",
            new_name="crm_stages_pipelin_f5dc4f_idx",
            old_name="crm_stages_pipelin_9e01f3_idx",
        ),
        migrations.RenameIndex(
            model_name="dealfirstzz",
            new_name="deal_first__first_z_a1bdbd_idx",
            old_name="deal_first__first_z_990169_idx",
        ),
        migrations.RenameIndex(
            model_name="dealfirstzz",
            new_name="deal_first__assigne_592e9a_idx",
            old_name="deal_first__assigne_a0c214_idx",
        ),
        migrations.RenameIndex(
            model_name="dealstageevent",
            new_name="deal_stage__deal_id_eb23a1_idx",
            old_name="deal_stage__deal_id_8bd4dc_idx",
        ),
        migrations.RenameIndex(
            model_name="dealstageevent",
            new_name="deal_stage__stage_i_36911b_idx",
            old_name="deal_stage__stage_i_5ca967_idx",
        ),
        migrations.RenameIndex(
            model_name="dealstageevent",
            new_name="deal_stage__assigne_9b51f4_idx",
            old_name="deal_stage__assigne_f08a43_idx",
        ),
        migrations.RenameIndex(
            model_name="managerdailymetric",
            new_name="manager_dai_metric__993eee_idx",
            old_name="manager_dai_metric__f1688d_idx",
        ),
        migrations.RenameIndex(
            model_name="managerdailymetric",
            new_name="manager_dai_manager_f2440a_idx",
            old_name="manager_dai_manager_40e04a_idx",
        ),
        migrations.RenameIndex(
            model_name="managerdailymetric",
            new_name="manager_dai_directi_5672b0_idx",
            old_name="manager_dai_directi_1ca1b6_idx",
        ),
        migrations.RenameIndex(
            model_name="syncrun",
            new_name="sync_runs_source_e4deba_idx",
            old_name="sync_runs_source__53367f_idx",
        ),
        migrations.RenameIndex(
            model_name="syncrun",
            new_name="sync_runs_status_947cca_idx",
            old_name="sync_runs_status__657735_idx",
        ),
    ]
