# Generated by Django 5.2.15 on 2026-08-19 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_rebuild_contract_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdirection',
            options={'ordering': ['name'], 'verbose_name': 'Направление бизнеса', 'verbose_name_plural': 'Направления бизнеса'},
        ),
        migrations.AlterModelOptions(
            name='crmdeal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='crmlead',
            options={'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
        migrations.AlterModelOptions(
            name='crmpipeline',
            options={'ordering': ['name'], 'verbose_name': 'Воронка', 'verbose_name_plural': 'Воронки'},
        ),
        migrations.AlterModelOptions(
            name='crmstage',
            options={'ordering': ['pipeline_id', 'sort', 'name'], 'verbose_name': 'Стадия сделки', 'verbose_name_plural': 'Стадии сделок'},
        ),
        migrations.AlterModelOptions(
            name='crmuser',
            options={'ordering': ['name'], 'verbose_name': 'Менеджер Bitrix', 'verbose_name_plural': 'Менеджеры Bitrix'},
        ),
        migrations.AlterModelOptions(
            name='dealfirstzz',
            options={'verbose_name': 'Первый ЗЗ', 'verbose_name_plural': 'Первые ЗЗ'},
        ),
        migrations.AlterModelOptions(
            name='dealstageevent',
            options={'verbose_name': 'Событие смены стадии', 'verbose_name_plural': 'События смены стадий'},
        ),
        migrations.AlterModelOptions(
            name='managerdailymetric',
            options={'verbose_name': 'Дневная метрика менеджера', 'verbose_name_plural': 'Дневные метрики менеджеров'},
        ),
        migrations.AlterModelOptions(
            name='synccursor',
            options={'verbose_name': 'Курсор синхронизации', 'verbose_name_plural': 'Курсоры синхронизации'},
        ),
        migrations.AlterModelOptions(
            name='syncrun',
            options={'verbose_name': 'Запуск синхронизации', 'verbose_name_plural': 'Запуски синхронизации'},
        ),
        migrations.AddField(
            model_name='dashboarduserprofile',
            name='allowed_directions',
            field=models.ManyToManyField(blank=True, to='analytics.businessdirection', verbose_name='Разрешенные направления'),
        ),
        migrations.AlterField(
            model_name='businessdirection',
            name='code',
            field=models.CharField(choices=[('panorama', 'Панорама'), ('ro', 'Русские окна'), ('b2b', 'B2B')], max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='businessdirection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='businessdirection',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmuser', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='bitrix_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID в Bitrix'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма договора'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='created_time',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.businessdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmlead', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='moved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmpipeline', verbose_name='Воронка'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmstage', verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmuser', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='bitrix_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID в Bitrix'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='created_time',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.businessdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='source_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='status_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='crmpipeline',
            name='bitrix_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='ID в Bitrix'),
        ),
        migrations.AlterField(
            model_name='crmpipeline',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.businessdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='crmpipeline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='crmpipeline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='crmpipeline',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='bitrix_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='ID в Bitrix'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Успешная'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='is_zn',
            field=models.BooleanField(default=False, verbose_name='Это ЗН'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='is_zz',
            field=models.BooleanField(default=False, verbose_name='Это ЗЗ'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmpipeline', verbose_name='Воронка'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='crmstage',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='bitrix_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID в Bitrix'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='dashboarduserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
        migrations.AlterField(
            model_name='dealfirstzz',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmuser', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='dealfirstzz',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_zz', to='analytics.crmdeal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='dealfirstzz',
            name='first_zz_at',
            field=models.DateTimeField(verbose_name='Первое попадание в ЗЗ'),
        ),
        migrations.AlterField(
            model_name='dealfirstzz',
            name='source',
            field=models.CharField(default='stage_history', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='dealfirstzz',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmstage', verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmuser', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='changed_at',
            field=models.DateTimeField(verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='analytics.crmdeal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='source_event_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID события'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.crmstage', verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='dealstageevent',
            name='stage_id_raw',
            field=models.CharField(max_length=128, verbose_name='Исходный ID стадии'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Сумма договоров'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='contracts',
            field=models.PositiveIntegerField(default=0, verbose_name='Договоры'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.businessdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='leads',
            field=models.PositiveIntegerField(default=0, verbose_name='Лиды'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.crmuser', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='metric_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='target_leads',
            field=models.PositiveIntegerField(default=0, verbose_name='Целевые лиды'),
        ),
        migrations.AlterField(
            model_name='managerdailymetric',
            name='zz',
            field=models.PositiveIntegerField(default=0, verbose_name='ЗЗ'),
        ),
        migrations.AlterField(
            model_name='synccursor',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='synccursor',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='synccursor',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='error',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='source',
            field=models.CharField(default='bitrix24', max_length=64, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], default='started', max_length=16, verbose_name='Статус'),
        ),
    ]
